### ISSUE TITLE
When load .yaml config file. the underline naming will change to Camel-Case.

### ISSUE THREAD

**Issue by abRev** [zeromicro/go-zero#2849]
OS: Linux
go-zero version : v1.4.3
goctl version 1.4.3 linux/amd64

when I upgrade from v1.2.3 to v1.4.3   , our code could`t working properly . 
because the underline naming will change to Camel-Case.

core/conf/config.go 
```
func LoadFromYamlBytes(content []byte, v interface{}) error {
	b, err := encoding.YamlToJson(content)
	if err != nil {
		return err
	}
	return LoadFromJsonBytes(b, v)
}
```

internal/encoding/enoding.go
```
func YamlToJson(data []byte) ([]byte, error) {
	var val interface{}
	if err := yaml.Unmarshal(data, &val); err != nil {
		return nil, err
	}

	val = toStringKeyMap(val)

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(val); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
```

**Comment by kevwan** [comment]
Thanks for reporting the issue! It's fixed in v1.4.4

**Comment by abRev** [comment]
I upgrade to v1.4.4. The problem still exists. of course， I also looked at the source code.  Did`t see any change.
Is it where I use it wrong？

**Comment by kevwan** [comment]
What's the config? Please show details.

**Comment by abRev** [comment]
```
redis:
  auth_third:
    addr: '*****'
    passwd: 'Czd@2021'
```
    
```conf.MustLoad(*configFile, &c)```
'auth_third' will become 'authThird'

**Comment by kevwan** [comment]
```go
package main

import (
	"flag"

	"github.com/davecgh/go-spew/spew"
	"github.com/zeromicro/go-zero/core/conf"
)

var configFile = flag.String("f", "config.yaml", "the config file")

type Config struct {
	Redis struct {
		AuthThird struct {
			Addr   string
			Passwd string
		} `json:"auth_third"`
	}
}

func main() {
	var c Config
	conf.MustLoad(*configFile, &c)
	spew.Dump(c)
}
```

The output is:

```
(main.Config) {
 Redis: (struct { AuthThird struct { Addr string; Passwd string } "json:\"auth_third\"" }) {
  AuthThird: (struct { Addr string; Passwd string }) {
   Addr: (string) (len=5) "*****",
   Passwd: (string) (len=8) "Czd@2021"
  }
 }
}
```

It works well.

**Comment by kevwan** [comment]
fixed.

**Comment by abanglou** [comment]
thanks~
